version: '3.4'
services:
    elasticsearch:
        image: elasticsearch:7.6.0
        container_name: elasticsearch
        # For development purposes a single node configuration should be sufficient
        environment:
          - discovery.type=single-node
        # Named volume "esdata01" for elasticsearch storage
        volumes:
          - esdata01:/usr/share/elasticsearch/data

    # Tooling for development
    # Kibana is a toolstack for elasticsearch administration
    # Additionally it provides tools for analysis and index optimization
    kibana:
        image: kibana:7.3.1
        container_name: kibana
        # Web GUI should be exposed on port 5601
        ports:
        - 5601:5601
        depends_on:
        - elasticsearch

    proxy:
        build:
            context: .
            dockerfile: docker/Dockerfile.proxy
        ports:
            - 8000:80
        depends_on:
        - os2phonebook-frontend
        - os2phonebook-backend

    os2phonebook-frontend:
        build:
            context: .
            dockerfile: docker/Dockerfile.frontend
        ports:
            - 4200:4200

    os2phonebook-backend:
        build:
            context: .
            dockerfile: docker/Dockerfile.backend
        ports:
            - 9090:9090
        environment:
            OS2PHONEBOOK_COMPANY_NAME: Magenta ApS
            OS2PHONEBOOK_DATALOADER_PASSWORD: password1
            ELASTICSEARCH_HOST: elasticsearch
            ELASTICSEARCH_PORT: 9200
        depends_on:
            - elasticsearch
volumes:
    esdata01:
        name: esdata01
        driver: local
