FROM tiangolo/meinheld-gunicorn-flask:python3.8-alpine3.11

# Default configuration (should be overridden)
ENV OS2PHONEBOOK_COMPANY_NAME=Magenta
ENV ELASTICSEARCH_HOST=elasticsearch
ENV ELASTICSEARCH_PORT=9200

# Create app folder
RUN mkdir -p /app
WORKDIR /app

# Install requirements
COPY os2phonebook_backend/requirements /app/requirements
RUN pip install --no-cache-dir -r /app/requirements/release.txt

# Copy in source
COPY os2phonebook_backend/preflight.sh /app/prestart.sh
COPY os2phonebook_backend/cli.py /app/cli.py
COPY os2phonebook_backend/wsgi.py /app/main.py
COPY os2phonebook_backend/os2phonebook /app/os2phonebook
