FROM node:14

COPY os2phonebook_gui /app

WORKDIR /app
RUN npm install

# Create service account / uid and gid
RUN groupadd -g 72085 -r sys_magenta_os2phonebook
RUN useradd -u 72085 --no-log-init -r -g sys_magenta_os2phonebook sys_magenta_os2phonebook

EXPOSE 4200

CMD ["npm", "run", "start"]
