FROM node:14-slim as builder

# Create app folder
RUN mkdir -p /app
WORKDIR /app

# Install requirements
COPY os2phonebook_frontend/package.json /app/package.json
COPY os2phonebook_frontend/package-lock.json /app/package-lock.json
RUN npm install

# Copy in source
COPY os2phonebook_frontend/ /app

# Compile source
RUN npm run build

FROM nginx:1.19-alpine
COPY --from=builder /app/dist/OS2PhonebookGUI /usr/share/nginx/html
