FROM node:14

RUN mkdir -p /app
WORKDIR /app

# Create service account / uid and gid
RUN groupadd -g 72085 -r sys_magenta_os2phonebook
RUN useradd -u 72085 --no-log-init -r -g sys_magenta_os2phonebook sys_magenta_os2phonebook

COPY os2phonebook_frontend/package.json /app/package.json
COPY os2phonebook_frontend/package-lock.json /app/package-lock.json
RUN npm install

COPY os2phonebook_frontend/ /app

EXPOSE 4200

CMD ["npm", "run", "start"]
