FROM python:3.7.4 AS dist
# Force the stdout and stderr streams from python to be unbuffered. See
# https://docs.python.org/3/using/cmdline.html#cmdoption-u
ENV PYTHONUNBUFFERED=1

COPY os2phonebook_service/cli.py /app/cli.py
COPY os2phonebook_service/wsgi.py /app/wsgi.py
COPY os2phonebook_service/requirements /app/requirements

# Install requirements
RUN pip install -r /app/requirements/release.txt

# Create service account / uid and gid
RUN groupadd -g 72085 -r sys_magenta_os2phonebook
RUN useradd -u 72085 --no-log-init -r -g sys_magenta_os2phonebook sys_magenta_os2phonebook

RUN mkdir /log

# Entrypoint
COPY docker/entrypoint.sh /entrypoint/os2phonebook-entrypoint.sh

# Copy in source
COPY os2phonebook_service/os2phonebook /app/os2phonebook

# Default configuration (should be overridden)
ENV OS2PHONEBOOK_COMPANY_NAME=Magenta
ENV OS2PHONEBOOK_LOG_ROOT=/log
ENV ELASTICSEARCH_HOST=elasticsearch
ENV ELASTICSEARCH_PORT=9200

# Set Permissions
RUN chown -R sys_magenta_os2phonebook:sys_magenta_os2phonebook /app
RUN chown -R sys_magenta_os2phonebook:sys_magenta_os2phonebook /log
RUN chown -R sys_magenta_os2phonebook:sys_magenta_os2phonebook /entrypoint

# USER sys_magenta_os2phonebook:sys_magenta_os2phonebook
RUN apt-get update && apt-get install --no-install-recommends -y sudo=1.8.27-1+deb10u5 \
    && apt-get clean && rm -rf /var/lib/apt/lists/*


WORKDIR /app

EXPOSE 9090

ENTRYPOINT ["sh", "/entrypoint/os2phonebook-entrypoint.sh"]

CMD ["gunicorn", "-b", "0.0.0.0:9090", "--worker-class=gevent", "--reload", "--worker-connections=1000", "wsgi:app"]
