FROM node:14-slim as builder

# Create app folder
RUN mkdir -p /app
WORKDIR /app

# Install requirements
COPY os2phonebook_frontend/package.json /app/package.json
COPY os2phonebook_frontend/package-lock.json /app/package-lock.json
RUN npm install

# Create service account / uid and gid
RUN groupadd -g 72085 -r sys_magenta_os2phonebook
RUN useradd -u 72085 --no-log-init -r -g sys_magenta_os2phonebook sys_magenta_os2phonebook

# Copy in source
COPY os2phonebook_frontend/ /app

# Compile source
CMD npm run build

FROM nginx:1.19-alpine
COPY --from=builder /app/dist/OS2PhonebookGUI /usr/share/nginx/html
